apiVersion: v1
kind: Service
metadata:
  name: restapi-service
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: restapi

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}

      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}