apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: postgresdb

  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.targetPort }}