apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-config
  namespace: student-api

data:
  POSTGRES_DB: students
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: student-api

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-deployment
  namespace: student-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgresdb

  template:
    metadata:
      labels:
        app: postgresdb

    spec:

      nodeSelector:
        type: database

      containers:
      - name: postgresdb

        image: postgres:15-alpine

        ports:
        - containerPort: 5432

        envFrom:
        - configMapRef:
            name: postgresdb-config

        - secretRef:
            name: db-secret

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
  namespace: student-api

spec:
  selector:
    app: postgresdb

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432