namespace: student-api

replicaCount: 2

image:
  repository: vikrantparalkar21/student-api
  tag: "c7bbce9"

service:
  type: NodePort
  port: 5000
  nodePort: 30000

postgres:
  image: postgres:15-alpine
  database: students
  user: postgres
  storage: 1Gi
  port: 5432
  targetPort: 5432
