name: fluidai-cicd

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "REST_API/*"

permissions:
  contents: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build-n-push :
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with: 
          python-version: "3.10"
        
      - name: Install Dependencies
        run: pip install -r ./REST_API/requirements.txt

      - name: Python flake8 Lint
        uses: py-actions/flake8@v2.3.0

      - name: Code Checks
        run: flake8 ./REST_API/
      
      - name: Testing
        run: pytest -v
        env:
          DATABASE_URL: "sqlite:///test.db"  
# Because during CI tests, PostgreSQL container is not running,
# So we use: sqlite:///test.db, which creates a small local test database automatically

      - name: Set short SHA
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
# $GITHUB_ENV is used to create GLOBAL environment variables between workflow steps.
      
      - name: docker build
        run: docker build -t ${DOCKER_USERNAME}/student-api:${TAG} .

      - name: docker login
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push
        run: docker push ${DOCKER_USERNAME}/student-api:${TAG}



  deploy :
    needs: build-n-push
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set short SHA
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
        
      - name: updating the "image tag" in values of helm
        run: |
          sed -i 's/tag:.*/tag: "'"${TAG}"'"/g' helm/student-api/values.yaml
          
      - name: git commit changes
        run: |
          git add helm/student-api/values.yaml
          git commit -m "image-tag updated"
          git push origin main
